// crates/fiducial-cli/components/svelte/Button.svelte
<script lang="ts">
  interface Props {
    variant?: "primary" | "secondary" | "ghost" | "destructive";
    size?: "sm" | "md" | "lg";
    disabled?: boolean;
    onclick?: () => void;
    type?: "button" | "submit" | "reset";
    class?: string;
    children?: import("svelte").Snippet;
  }

  let {
    variant = "primary",
    size = "md",
    disabled = false,
    onclick,
    type = "button",
    class: className,
    children,
  }: Props = $props();
</script>

<button
  {type}
  {disabled}
  {onclick}
  data-variant={variant}
  data-size={size}
  class={["fid-btn", className].filter(Boolean).join(" ")}
>
  {@render children?.()}
</button>

<style>
  :global(.fid-btn) {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    gap: 0.375rem;
    border-radius: var(--radius);
    font-size: 0.875rem;
    font-weight: 500;
    line-height: 1;
    cursor: pointer;
    border: 1px solid transparent;
    transition: opacity 0.15s, background 0.15s;
    white-space: nowrap;
    user-select: none;
  }
  :global(.fid-btn:disabled) { opacity: 0.5; cursor: not-allowed; pointer-events: none; }
  :global(.fid-btn[data-size="sm"]) { padding: 0.375rem 0.75rem; font-size: 0.8125rem; }
  :global(.fid-btn[data-size="md"]) { padding: 0.5rem 1rem; }
  :global(.fid-btn[data-size="lg"]) { padding: 0.625rem 1.25rem; font-size: 1rem; }
  :global(.fid-btn[data-variant="primary"]) { background: var(--primary); color: var(--primary-foreground); }
  :global(.fid-btn[data-variant="primary"]:hover:not(:disabled)) { opacity: 0.9; }
  :global(.fid-btn[data-variant="secondary"]) { background: var(--secondary); color: var(--secondary-foreground); border-color: var(--border); }
  :global(.fid-btn[data-variant="secondary"]:hover:not(:disabled)) { background: var(--accent); }
  :global(.fid-btn[data-variant="ghost"]) { background: transparent; color: var(--foreground); }
  :global(.fid-btn[data-variant="ghost"]:hover:not(:disabled)) { background: var(--accent); color: var(--accent-foreground); }
  :global(.fid-btn[data-variant="destructive"]) { background: var(--destructive); color: var(--primary-foreground); }
  :global(.fid-btn[data-variant="destructive"]:hover:not(:disabled)) { opacity: 0.9; }
</style>

// packages/ui-react/src/button.tsx
import * as React from "react";
import { cva, type VariantProps } from "class-variance-authority";
import { cn } from "./lib/utils";

const buttonVariants = cva(
  "inline-flex items-center justify-center gap-1.5 whitespace-nowrap rounded-md text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50",
  {
    variants: {
      variant: {
        default:     "bg-primary text-primary-foreground shadow hover:bg-primary/90",
        destructive: "bg-destructive text-destructive-foreground shadow-sm hover:bg-destructive/90",
        outline:     "border border-input bg-background shadow-sm hover:bg-accent hover:text-accent-foreground",
        secondary:   "bg-secondary text-secondary-foreground shadow-sm hover:bg-secondary/80",
        ghost:       "hover:bg-accent hover:text-accent-foreground",
        link:        "text-primary underline-offset-4 hover:underline",
      },
      size: {
        default: "h-9 px-4 py-2",
        sm:      "h-8 rounded-md px-3 text-xs",
        lg:      "h-10 rounded-md px-8",
        icon:    "h-9 w-9",
      },
    },
    defaultVariants: {
      variant: "default",
      size:    "default",
    },
  },
);

export interface ButtonProps
  extends React.ButtonHTMLAttributes<HTMLButtonElement>,
    VariantProps<typeof buttonVariants> {}

export function Button({ className, variant, size, ...props }: ButtonProps) {
  return (
    <button
      className={cn(buttonVariants({ variant, size, className }))}
      {...props}
    />
  );
}

export { buttonVariants };
