// packages/ui-svelte/src/StatusBadge.svelte
<script lang="ts" generics="T, E">
  import type { Result } from "@fiducial/headless";

  interface Props {
    result: Result<T, E>;
    renderOk?: (value: T) => string;
    renderErr?: (error: E) => string;
  }

  let {
    result,
    renderOk = String,
    renderErr = String,
  }: Props = $props();
</script>

{#if result.ok}
  <span class="badge badge-ok">✓ {renderOk(result.value)}</span>
{:else}
  <span class="badge badge-err">✗ {renderErr(result.error)}</span>
{/if}

<style>
  .badge {
    display: inline-flex;
    align-items: center;
    gap: 0.375rem;
    padding: 0.25rem 0.75rem;
    border-radius: 9999px;
    font-size: 0.75rem;
    font-weight: 500;
  }

  .badge-ok {
    background: var(--secondary);
    color: var(--secondary-foreground);
  }

  .badge-err {
    background: color-mix(in oklch, var(--destructive) 15%, transparent);
    color: var(--destructive);
  }
</style>

// packages/ui-react/src/StatusBadge.tsx
import type { Result } from "@fiducial/headless";
import type { CSSProperties } from "react";

export interface StatusBadgeProps<T, E> {
  result: Result<T, E>;
  renderOk?: (value: T) => string;
  renderErr?: (error: E) => string;
}

const baseStyle: CSSProperties = {
  display: "inline-flex",
  alignItems: "center",
  gap: "0.375rem",
  padding: "0.25rem 0.75rem",
  borderRadius: "9999px",
  fontSize: "0.75rem",
  fontWeight: 500,
};

export function StatusBadge<T, E>({
  result,
  renderOk = String,
  renderErr = String,
}: StatusBadgeProps<T, E>) {
  if (result.ok) {
    return (
      <span
        style={{
          ...baseStyle,
          background: "var(--secondary)",
          color: "var(--secondary-foreground)",
        }}
      >
        ✓ {renderOk(result.value)}
      </span>
    );
  }
  return (
    <span
      style={{
        ...baseStyle,
        background: "color-mix(in oklch, var(--destructive) 15%, transparent)",
        color: "var(--destructive)",
      }}
    >
      ✗ {renderErr(result.error)}
    </span>
  );
}
